twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        static: '@App\Service\StaticService'
        bridge: '@App\Service\BridgeService'

when@test:
    twig:
        strict_variables: true
