version: '3.9'

services:
    db:
        image: postgres:15-alpine
        restart: on-failure
        environment:
            POSTGRES_DB: ???
            POSTGRES_USER: ???
            POSTGRES_PASSWORD: ???
            PGDATA: /var/lib/postgresql/data
        volumes:
            - ./db:/var/lib/postgresql/data:rw
    web:
        image: ubuntu:20.04
        expose:
            - 80:80
            - 443:443
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
