version: "3"
services:
  postgres:
    image: postgres:15.1-alpine
    networks:
      - internal
    environment:
      - POSTGRES_USER=tetra
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tetra
  migrate-seed:
    build:
      context: .
      dockerfile: docker/job.Dockerfile
    entrypoint: php artisan migrate && php artisan db:seed
    networks:
      - internal
    environment:
      - POSTGRES_USER=tetra
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tetra
    depends_on:
      - postgres
  queue-work:
    build:
      context: .
      dockerfile: docker/job.Dockerfile
    entrypoint: php artisan queue:work
    networks:
      - internal
    environment:
      - POSTGRES_USER=tetra
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tetra
    depends_on:
      - postgres
  schedule-run:
    build:
      context: .
      dockerfile: docker/job.Dockerfile
    entrypoint: while true; do php artisan schedule:run && sleep 60; done
    networks:
      - internal
    environment:
      - POSTGRES_USER=tetra
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tetra
    depends_on:
      - postgres
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal
    depends_on:
      - server
  server:
    build:
      context: .
      dockerfile: docker/server.Dockerfile
    networks:
      - internal
    depends_on:
      - postgres
      - migrate-seed
networks:
  internal:
    driver: bridge
