/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List public user profiles
         * @description Requires an administrator API key.
         */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/api-key-info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get API key regeneration availability */
        get: operations["getAPIKeyInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/regenerate-api-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate the current user's API key */
        post: operations["regenerateAPIKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shortlinks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the current user's active shortlinks */
        get: operations["listShortlinks"];
        /**
         * Create a shortlink
         * @description An API key is optional. When supplied, the new shortlink is associated with that user.
         */
        put: operations["createShortlink"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shortlinks/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all shortlinks
         * @description Requires an administrator API key. Unlike user and public reads, this includes disabled and not-yet-cleaned expired shortlinks.
         */
        get: operations["listAllShortlinks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shortlinks/{shortcode}/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check whether a shortcode is available */
        get: operations["isShortcodeAvailable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shortlinks/{shortcode}/{secret}/set-expiry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set a shortlink's expiration time */
        patch: operations["setShortlinkExpiry"];
        trace?: never;
    };
    "/api/v1/shortlinks/{shortcode}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Toggle whether a shortlink is disabled
         * @description Requires an administrator API key.
         */
        patch: operations["toggleShortlink"];
        trace?: never;
    };
    "/api/v1/shortlinks/{shortcode}/{secret}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a shortlink using its management secret */
        delete: operations["deleteShortlink"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shortlinks/{shortcode}/{secret}/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete a shortlink using its management secret
         * @deprecated
         * @description Legacy POST variant of DELETE /api/v1/shortlinks/{shortcode}/{secret}.
         */
        post: operations["deleteShortlinkLegacy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shortlinks/{shortcode}/qr.svg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an SVG QR code for an active shortlink */
        get: operations["getShortlinkQRCode"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shortlinks/{shortcode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get public information about an active shortlink */
        get: operations["getShortlink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @description Request correlation identifier */
            requestId: string;
            code: number;
            message: string;
        };
        PublicUser: {
            username: string;
            /** Format: uri */
            avatar: string;
            admin: boolean;
        };
        ListUsersResponse: components["schemas"]["PublicUser"][];
        APIKeyInfo: {
            canRegenerate: boolean;
            /** Format: date-time */
            nextApiKeyAvailable: string;
        };
        RegenerateAPIKeyResponse: {
            /** Format: uuid */
            apiKey: string;
        };
        CreateShortlinkBody: {
            /**
             * Format: uri
             * @description Absolute HTTP or HTTPS destination URL
             */
            destination: string;
            /** @description Optional custom shortcode. Reserved values are rejected case-insensitively. */
            shortcode?: string;
            /**
             * @description Optional human-readable lifetime parsed by github.com/depthbomb/duration. It must resolve to at least one minute.
             * @example 15m
             * @example 2 days
             * @example 1 week
             * @example 2 days and 6 hours
             */
            duration?: string;
        };
        SetExpiryBody: {
            /**
             * @description Human-readable lifetime parsed by github.com/depthbomb/duration. It must resolve to at least one minute.
             * @example 15m
             * @example 2 days
             * @example 1 week
             */
            duration: string;
        };
        PublicShortlink: {
            shortcode: string;
            /** Format: uri */
            shortlink: string;
            /** Format: uri */
            destination: string;
            /** Format: int64 */
            hits: number;
            /** Format: date-time */
            createdAt: string;
            /**
             * Format: date-time
             * @description Expiration time, or null when the shortlink never expires
             */
            expiresAt: string | null;
        };
        OwnedShortlink: components["schemas"]["PublicShortlink"] & {
            secret: string;
        };
        ShortlinkCreator: {
            username: string;
        };
        AdminShortlink: components["schemas"]["OwnedShortlink"] & {
            creatorIp: string;
            /** @description Creator profile, or null for an anonymously created shortlink */
            user: components["schemas"]["ShortlinkCreator"] | null;
            disabled: boolean;
        };
        CreateShortlinkResponse: {
            shortcode: string;
            /** Format: uri */
            shortlink: string;
            /** Format: uri */
            destination: string;
            secret: string;
            /**
             * Format: date-time
             * @description Expiration time, or null when the shortlink never expires
             */
            expiresAt: string | null;
        };
        ListShortlinksResponse: components["schemas"]["OwnedShortlink"][];
        ListAllShortlinksResponse: components["schemas"]["AdminShortlink"][];
        ShortcodeAvailabilityResponse: {
            available: boolean;
        };
        SetExpiryResponse: {
            /** Format: date-time */
            expiresAt: string;
        };
        ToggleShortlinkResponse: {
            disabled: boolean;
        };
        DeleteShortlinkResponse: {
            /** @constant */
            success: true;
        };
    };
    responses: {
        /** @description The request is invalid */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication is required or the supplied credentials are invalid */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The authenticated user is not permitted to perform this operation */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The shortlink was not found, is disabled, or has expired */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The requested shortcode is already in use */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The request body exceeds the configured limit */
        ContentTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description An unexpected server error occurred */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description API key query parameter. On protected operations, either this parameter or X-Api-Key is required. */
        ApiKeyQuery: string;
        /** @description API key header. Used when apiKey is absent from the query string. */
        ApiKeyHeader: string;
        /** @description A 3-64 character shortcode. The values api, go, health, oidc, ready, and sse are reserved, case-insensitively. */
        Shortcode: string;
        /** @description The 64-character management secret returned when the shortlink was created. */
        Secret: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listUsers: {
        parameters: {
            query?: {
                /** @description API key query parameter. On protected operations, either this parameter or X-Api-Key is required. */
                apiKey?: components["parameters"]["ApiKeyQuery"];
            };
            header?: {
                /** @description API key header. Used when apiKey is absent from the query string. */
                "X-Api-Key"?: components["parameters"]["ApiKeyHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public user profiles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListUsersResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getAPIKeyInfo: {
        parameters: {
            query?: {
                /** @description API key query parameter. On protected operations, either this parameter or X-Api-Key is required. */
                apiKey?: components["parameters"]["ApiKeyQuery"];
            };
            header?: {
                /** @description API key header. Used when apiKey is absent from the query string. */
                "X-Api-Key"?: components["parameters"]["ApiKeyHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API key regeneration information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIKeyInfo"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    regenerateAPIKey: {
        parameters: {
            query?: {
                /** @description API key query parameter. On protected operations, either this parameter or X-Api-Key is required. */
                apiKey?: components["parameters"]["ApiKeyQuery"];
            };
            header?: {
                /** @description API key header. Used when apiKey is absent from the query string. */
                "X-Api-Key"?: components["parameters"]["ApiKeyHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The newly generated API key */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegenerateAPIKeyResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listShortlinks: {
        parameters: {
            query?: {
                /** @description API key query parameter. On protected operations, either this parameter or X-Api-Key is required. */
                apiKey?: components["parameters"]["ApiKeyQuery"];
            };
            header?: {
                /** @description API key header. Used when apiKey is absent from the query string. */
                "X-Api-Key"?: components["parameters"]["ApiKeyHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shortlinks owned by the API key user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListShortlinksResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            500: components["responses"]["InternalServerError"];
        };
    };
    createShortlink: {
        parameters: {
            query?: {
                /** @description API key query parameter. On protected operations, either this parameter or X-Api-Key is required. */
                apiKey?: components["parameters"]["ApiKeyQuery"];
            };
            header?: {
                /** @description API key header. Used when apiKey is absent from the query string. */
                "X-Api-Key"?: components["parameters"]["ApiKeyHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShortlinkBody"];
            };
        };
        responses: {
            /** @description Shortlink created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateShortlinkResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            413: components["responses"]["ContentTooLarge"];
            500: components["responses"]["InternalServerError"];
        };
    };
    listAllShortlinks: {
        parameters: {
            query?: {
                /** @description API key query parameter. On protected operations, either this parameter or X-Api-Key is required. */
                apiKey?: components["parameters"]["ApiKeyQuery"];
            };
            header?: {
                /** @description API key header. Used when apiKey is absent from the query string. */
                "X-Api-Key"?: components["parameters"]["ApiKeyHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All shortlinks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAllShortlinksResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            500: components["responses"]["InternalServerError"];
        };
    };
    isShortcodeAvailable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A 3-64 character shortcode. The values api, go, health, oidc, ready, and sse are reserved, case-insensitively. */
                shortcode: components["parameters"]["Shortcode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shortcode availability */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShortcodeAvailabilityResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalServerError"];
        };
    };
    setShortlinkExpiry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A 3-64 character shortcode. The values api, go, health, oidc, ready, and sse are reserved, case-insensitively. */
                shortcode: components["parameters"]["Shortcode"];
                /** @description The 64-character management secret returned when the shortlink was created. */
                secret: components["parameters"]["Secret"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetExpiryBody"];
            };
        };
        responses: {
            /** @description Updated expiration time */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetExpiryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            413: components["responses"]["ContentTooLarge"];
            500: components["responses"]["InternalServerError"];
        };
    };
    toggleShortlink: {
        parameters: {
            query?: {
                /** @description API key query parameter. On protected operations, either this parameter or X-Api-Key is required. */
                apiKey?: components["parameters"]["ApiKeyQuery"];
            };
            header?: {
                /** @description API key header. Used when apiKey is absent from the query string. */
                "X-Api-Key"?: components["parameters"]["ApiKeyHeader"];
            };
            path: {
                /** @description A 3-64 character shortcode. The values api, go, health, oidc, ready, and sse are reserved, case-insensitively. */
                shortcode: components["parameters"]["Shortcode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The shortlink's new disabled state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToggleShortlinkResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteShortlink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A 3-64 character shortcode. The values api, go, health, oidc, ready, and sse are reserved, case-insensitively. */
                shortcode: components["parameters"]["Shortcode"];
                /** @description The 64-character management secret returned when the shortlink was created. */
                secret: components["parameters"]["Secret"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shortlink deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteShortlinkResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    deleteShortlinkLegacy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A 3-64 character shortcode. The values api, go, health, oidc, ready, and sse are reserved, case-insensitively. */
                shortcode: components["parameters"]["Shortcode"];
                /** @description The 64-character management secret returned when the shortlink was created. */
                secret: components["parameters"]["Secret"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shortlink deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteShortlinkResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getShortlinkQRCode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A 3-64 character shortcode. The values api, go, health, oidc, ready, and sse are reserved, case-insensitively. */
                shortcode: components["parameters"]["Shortcode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SVG QR code containing the shortlink URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/svg+xml": string;
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
    getShortlink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A 3-64 character shortcode. The values api, go, health, oidc, ready, and sse are reserved, case-insensitively. */
                shortcode: components["parameters"]["Shortcode"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public shortlink information */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicShortlink"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalServerError"];
        };
    };
}
