apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: postgresql
spec:
  databases:
    tetra: tetra
  enableShmVolume: true
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: super.fish/storage-class-ssd
              operator: In
              values:
                - "true"
  numberOfInstances: 2
  postgresql:
    version: "15"
  resources:
    limits:
      cpu: "1"
      memory: 2Gi
    requests:
      cpu: 50m
      memory: 256Mi
  teamId: tetra
  users:
    tetra:
      - superuser
      - createdb
  volume:
    size: 20Gi
    storageClass: ssd
