apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetra
  labels:
    app: tetra
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tetra
  template:
    metadata:
      labels:
        app: tetra
    spec:
      containers:
        - name: tetra
          image: tetra
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /ready
              port: http
          livenessProbe:
            httpGet:
              path: /health
              port: http
          ports:
            - name: http
              containerPort: 80
          env:
            - name: PORT
              value: "80"
          envFrom:
            - secretRef:
                name: tetra-env
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: tetra
  labels:
    app.kubernetes.io/name: tetra
spec:
  selector:
    app.kubernetes.io/name: tetra
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tetra
spec:
  rules:
    - host: go.super.fish
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tetra
                port:
                  name: http
  tls:
    - hosts:
        - go.super.fish
      secretName: go.super.fish
