#!/bin/bash
PUBLIC_DIR=!ChangeMe!
RANDOM_NAME=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 13)
echo "<?php opcache_reset(); ?>" > ${PUBLIC_DIR}${RANDOM_NAME}.php
curl http://localhost/${RANDOM_NAME}.php
rm ${PUBLIC_DIR}${RANDOM_NAME}.php

# Adapted from https://www.php.net/manual/en/function.opcache-reset.php#121513
