// Code generated by ent, DO NOT EDIT.

package shortlink

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the shortlink type in the database.
	Label = "shortlink"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatorIP holds the string denoting the creator_ip field in the database.
	FieldCreatorIP = "creator_ip"
	// FieldShortcode holds the string denoting the shortcode field in the database.
	FieldShortcode = "shortcode"
	// FieldShortlink holds the string denoting the shortlink field in the database.
	FieldShortlink = "shortlink"
	// FieldDestination holds the string denoting the destination field in the database.
	FieldDestination = "destination"
	// FieldSecretKey holds the string denoting the secret_key field in the database.
	FieldSecretKey = "secret_key"
	// FieldHits holds the string denoting the hits field in the database.
	FieldHits = "hits"
	// FieldValidated holds the string denoting the validated field in the database.
	FieldValidated = "validated"
	// FieldDisabled holds the string denoting the disabled field in the database.
	FieldDisabled = "disabled"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// EdgeCreator holds the string denoting the creator edge name in mutations.
	EdgeCreator = "creator"
	// Table holds the table name of the shortlink in the database.
	Table = "shortlinks"
	// CreatorTable is the table that holds the creator relation/edge.
	CreatorTable = "shortlinks"
	// CreatorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	CreatorInverseTable = "users"
	// CreatorColumn is the table column denoting the creator relation/edge.
	CreatorColumn = "user_shortlinks"
)

// Columns holds all SQL columns for shortlink fields.
var Columns = []string{
	FieldID,
	FieldCreatorIP,
	FieldShortcode,
	FieldShortlink,
	FieldDestination,
	FieldSecretKey,
	FieldHits,
	FieldValidated,
	FieldDisabled,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldExpiresAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "shortlinks"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_shortlinks",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// CreatorIPValidator is a validator for the "creator_ip" field. It is called by the builders before save.
	CreatorIPValidator func(string) error
	// ShortcodeValidator is a validator for the "shortcode" field. It is called by the builders before save.
	ShortcodeValidator func(string) error
	// ShortlinkValidator is a validator for the "shortlink" field. It is called by the builders before save.
	ShortlinkValidator func(string) error
	// DestinationValidator is a validator for the "destination" field. It is called by the builders before save.
	DestinationValidator func(string) error
	// SecretKeyValidator is a validator for the "secret_key" field. It is called by the builders before save.
	SecretKeyValidator func(string) error
	// DefaultHits holds the default value on creation for the "hits" field.
	DefaultHits int64
	// DefaultValidated holds the default value on creation for the "validated" field.
	DefaultValidated bool
	// DefaultDisabled holds the default value on creation for the "disabled" field.
	DefaultDisabled bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Shortlink queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatorIP orders the results by the creator_ip field.
func ByCreatorIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatorIP, opts...).ToFunc()
}

// ByShortcode orders the results by the shortcode field.
func ByShortcode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShortcode, opts...).ToFunc()
}

// ByShortlink orders the results by the shortlink field.
func ByShortlink(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShortlink, opts...).ToFunc()
}

// ByDestination orders the results by the destination field.
func ByDestination(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDestination, opts...).ToFunc()
}

// BySecretKey orders the results by the secret_key field.
func BySecretKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSecretKey, opts...).ToFunc()
}

// ByHits orders the results by the hits field.
func ByHits(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHits, opts...).ToFunc()
}

// ByValidated orders the results by the validated field.
func ByValidated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldValidated, opts...).ToFunc()
}

// ByDisabled orders the results by the disabled field.
func ByDisabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisabled, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// ByCreatorField orders the results by creator field.
func ByCreatorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatorStep(), sql.OrderByField(field, opts...))
	}
}
func newCreatorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CreatorTable, CreatorColumn),
	)
}
