// Code generated by ent, DO NOT EDIT.

package shortlink

import (
	"go-tetra/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldLTE(FieldID, id))
}

// CreatorIP applies equality check predicate on the "creator_ip" field. It's identical to CreatorIPEQ.
func CreatorIP(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEQ(FieldCreatorIP, v))
}

// Shortcode applies equality check predicate on the "shortcode" field. It's identical to ShortcodeEQ.
func Shortcode(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEQ(FieldShortcode, v))
}

// Shortlink applies equality check predicate on the "shortlink" field. It's identical to ShortlinkEQ.
func Shortlink(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEQ(FieldShortlink, v))
}

// Destination applies equality check predicate on the "destination" field. It's identical to DestinationEQ.
func Destination(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEQ(FieldDestination, v))
}

// SecretKey applies equality check predicate on the "secret_key" field. It's identical to SecretKeyEQ.
func SecretKey(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEQ(FieldSecretKey, v))
}

// Hits applies equality check predicate on the "hits" field. It's identical to HitsEQ.
func Hits(v int64) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEQ(FieldHits, v))
}

// Validated applies equality check predicate on the "validated" field. It's identical to ValidatedEQ.
func Validated(v bool) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEQ(FieldValidated, v))
}

// Disabled applies equality check predicate on the "disabled" field. It's identical to DisabledEQ.
func Disabled(v bool) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEQ(FieldDisabled, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEQ(FieldUpdatedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEQ(FieldExpiresAt, v))
}

// CreatorIPEQ applies the EQ predicate on the "creator_ip" field.
func CreatorIPEQ(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEQ(FieldCreatorIP, v))
}

// CreatorIPNEQ applies the NEQ predicate on the "creator_ip" field.
func CreatorIPNEQ(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldNEQ(FieldCreatorIP, v))
}

// CreatorIPIn applies the In predicate on the "creator_ip" field.
func CreatorIPIn(vs ...string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldIn(FieldCreatorIP, vs...))
}

// CreatorIPNotIn applies the NotIn predicate on the "creator_ip" field.
func CreatorIPNotIn(vs ...string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldNotIn(FieldCreatorIP, vs...))
}

// CreatorIPGT applies the GT predicate on the "creator_ip" field.
func CreatorIPGT(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldGT(FieldCreatorIP, v))
}

// CreatorIPGTE applies the GTE predicate on the "creator_ip" field.
func CreatorIPGTE(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldGTE(FieldCreatorIP, v))
}

// CreatorIPLT applies the LT predicate on the "creator_ip" field.
func CreatorIPLT(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldLT(FieldCreatorIP, v))
}

// CreatorIPLTE applies the LTE predicate on the "creator_ip" field.
func CreatorIPLTE(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldLTE(FieldCreatorIP, v))
}

// CreatorIPContains applies the Contains predicate on the "creator_ip" field.
func CreatorIPContains(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldContains(FieldCreatorIP, v))
}

// CreatorIPHasPrefix applies the HasPrefix predicate on the "creator_ip" field.
func CreatorIPHasPrefix(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldHasPrefix(FieldCreatorIP, v))
}

// CreatorIPHasSuffix applies the HasSuffix predicate on the "creator_ip" field.
func CreatorIPHasSuffix(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldHasSuffix(FieldCreatorIP, v))
}

// CreatorIPEqualFold applies the EqualFold predicate on the "creator_ip" field.
func CreatorIPEqualFold(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEqualFold(FieldCreatorIP, v))
}

// CreatorIPContainsFold applies the ContainsFold predicate on the "creator_ip" field.
func CreatorIPContainsFold(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldContainsFold(FieldCreatorIP, v))
}

// ShortcodeEQ applies the EQ predicate on the "shortcode" field.
func ShortcodeEQ(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEQ(FieldShortcode, v))
}

// ShortcodeNEQ applies the NEQ predicate on the "shortcode" field.
func ShortcodeNEQ(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldNEQ(FieldShortcode, v))
}

// ShortcodeIn applies the In predicate on the "shortcode" field.
func ShortcodeIn(vs ...string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldIn(FieldShortcode, vs...))
}

// ShortcodeNotIn applies the NotIn predicate on the "shortcode" field.
func ShortcodeNotIn(vs ...string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldNotIn(FieldShortcode, vs...))
}

// ShortcodeGT applies the GT predicate on the "shortcode" field.
func ShortcodeGT(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldGT(FieldShortcode, v))
}

// ShortcodeGTE applies the GTE predicate on the "shortcode" field.
func ShortcodeGTE(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldGTE(FieldShortcode, v))
}

// ShortcodeLT applies the LT predicate on the "shortcode" field.
func ShortcodeLT(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldLT(FieldShortcode, v))
}

// ShortcodeLTE applies the LTE predicate on the "shortcode" field.
func ShortcodeLTE(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldLTE(FieldShortcode, v))
}

// ShortcodeContains applies the Contains predicate on the "shortcode" field.
func ShortcodeContains(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldContains(FieldShortcode, v))
}

// ShortcodeHasPrefix applies the HasPrefix predicate on the "shortcode" field.
func ShortcodeHasPrefix(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldHasPrefix(FieldShortcode, v))
}

// ShortcodeHasSuffix applies the HasSuffix predicate on the "shortcode" field.
func ShortcodeHasSuffix(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldHasSuffix(FieldShortcode, v))
}

// ShortcodeEqualFold applies the EqualFold predicate on the "shortcode" field.
func ShortcodeEqualFold(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEqualFold(FieldShortcode, v))
}

// ShortcodeContainsFold applies the ContainsFold predicate on the "shortcode" field.
func ShortcodeContainsFold(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldContainsFold(FieldShortcode, v))
}

// ShortlinkEQ applies the EQ predicate on the "shortlink" field.
func ShortlinkEQ(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEQ(FieldShortlink, v))
}

// ShortlinkNEQ applies the NEQ predicate on the "shortlink" field.
func ShortlinkNEQ(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldNEQ(FieldShortlink, v))
}

// ShortlinkIn applies the In predicate on the "shortlink" field.
func ShortlinkIn(vs ...string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldIn(FieldShortlink, vs...))
}

// ShortlinkNotIn applies the NotIn predicate on the "shortlink" field.
func ShortlinkNotIn(vs ...string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldNotIn(FieldShortlink, vs...))
}

// ShortlinkGT applies the GT predicate on the "shortlink" field.
func ShortlinkGT(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldGT(FieldShortlink, v))
}

// ShortlinkGTE applies the GTE predicate on the "shortlink" field.
func ShortlinkGTE(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldGTE(FieldShortlink, v))
}

// ShortlinkLT applies the LT predicate on the "shortlink" field.
func ShortlinkLT(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldLT(FieldShortlink, v))
}

// ShortlinkLTE applies the LTE predicate on the "shortlink" field.
func ShortlinkLTE(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldLTE(FieldShortlink, v))
}

// ShortlinkContains applies the Contains predicate on the "shortlink" field.
func ShortlinkContains(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldContains(FieldShortlink, v))
}

// ShortlinkHasPrefix applies the HasPrefix predicate on the "shortlink" field.
func ShortlinkHasPrefix(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldHasPrefix(FieldShortlink, v))
}

// ShortlinkHasSuffix applies the HasSuffix predicate on the "shortlink" field.
func ShortlinkHasSuffix(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldHasSuffix(FieldShortlink, v))
}

// ShortlinkEqualFold applies the EqualFold predicate on the "shortlink" field.
func ShortlinkEqualFold(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEqualFold(FieldShortlink, v))
}

// ShortlinkContainsFold applies the ContainsFold predicate on the "shortlink" field.
func ShortlinkContainsFold(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldContainsFold(FieldShortlink, v))
}

// DestinationEQ applies the EQ predicate on the "destination" field.
func DestinationEQ(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEQ(FieldDestination, v))
}

// DestinationNEQ applies the NEQ predicate on the "destination" field.
func DestinationNEQ(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldNEQ(FieldDestination, v))
}

// DestinationIn applies the In predicate on the "destination" field.
func DestinationIn(vs ...string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldIn(FieldDestination, vs...))
}

// DestinationNotIn applies the NotIn predicate on the "destination" field.
func DestinationNotIn(vs ...string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldNotIn(FieldDestination, vs...))
}

// DestinationGT applies the GT predicate on the "destination" field.
func DestinationGT(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldGT(FieldDestination, v))
}

// DestinationGTE applies the GTE predicate on the "destination" field.
func DestinationGTE(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldGTE(FieldDestination, v))
}

// DestinationLT applies the LT predicate on the "destination" field.
func DestinationLT(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldLT(FieldDestination, v))
}

// DestinationLTE applies the LTE predicate on the "destination" field.
func DestinationLTE(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldLTE(FieldDestination, v))
}

// DestinationContains applies the Contains predicate on the "destination" field.
func DestinationContains(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldContains(FieldDestination, v))
}

// DestinationHasPrefix applies the HasPrefix predicate on the "destination" field.
func DestinationHasPrefix(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldHasPrefix(FieldDestination, v))
}

// DestinationHasSuffix applies the HasSuffix predicate on the "destination" field.
func DestinationHasSuffix(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldHasSuffix(FieldDestination, v))
}

// DestinationEqualFold applies the EqualFold predicate on the "destination" field.
func DestinationEqualFold(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEqualFold(FieldDestination, v))
}

// DestinationContainsFold applies the ContainsFold predicate on the "destination" field.
func DestinationContainsFold(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldContainsFold(FieldDestination, v))
}

// SecretKeyEQ applies the EQ predicate on the "secret_key" field.
func SecretKeyEQ(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEQ(FieldSecretKey, v))
}

// SecretKeyNEQ applies the NEQ predicate on the "secret_key" field.
func SecretKeyNEQ(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldNEQ(FieldSecretKey, v))
}

// SecretKeyIn applies the In predicate on the "secret_key" field.
func SecretKeyIn(vs ...string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldIn(FieldSecretKey, vs...))
}

// SecretKeyNotIn applies the NotIn predicate on the "secret_key" field.
func SecretKeyNotIn(vs ...string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldNotIn(FieldSecretKey, vs...))
}

// SecretKeyGT applies the GT predicate on the "secret_key" field.
func SecretKeyGT(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldGT(FieldSecretKey, v))
}

// SecretKeyGTE applies the GTE predicate on the "secret_key" field.
func SecretKeyGTE(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldGTE(FieldSecretKey, v))
}

// SecretKeyLT applies the LT predicate on the "secret_key" field.
func SecretKeyLT(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldLT(FieldSecretKey, v))
}

// SecretKeyLTE applies the LTE predicate on the "secret_key" field.
func SecretKeyLTE(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldLTE(FieldSecretKey, v))
}

// SecretKeyContains applies the Contains predicate on the "secret_key" field.
func SecretKeyContains(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldContains(FieldSecretKey, v))
}

// SecretKeyHasPrefix applies the HasPrefix predicate on the "secret_key" field.
func SecretKeyHasPrefix(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldHasPrefix(FieldSecretKey, v))
}

// SecretKeyHasSuffix applies the HasSuffix predicate on the "secret_key" field.
func SecretKeyHasSuffix(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldHasSuffix(FieldSecretKey, v))
}

// SecretKeyEqualFold applies the EqualFold predicate on the "secret_key" field.
func SecretKeyEqualFold(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEqualFold(FieldSecretKey, v))
}

// SecretKeyContainsFold applies the ContainsFold predicate on the "secret_key" field.
func SecretKeyContainsFold(v string) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldContainsFold(FieldSecretKey, v))
}

// HitsEQ applies the EQ predicate on the "hits" field.
func HitsEQ(v int64) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEQ(FieldHits, v))
}

// HitsNEQ applies the NEQ predicate on the "hits" field.
func HitsNEQ(v int64) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldNEQ(FieldHits, v))
}

// HitsIn applies the In predicate on the "hits" field.
func HitsIn(vs ...int64) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldIn(FieldHits, vs...))
}

// HitsNotIn applies the NotIn predicate on the "hits" field.
func HitsNotIn(vs ...int64) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldNotIn(FieldHits, vs...))
}

// HitsGT applies the GT predicate on the "hits" field.
func HitsGT(v int64) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldGT(FieldHits, v))
}

// HitsGTE applies the GTE predicate on the "hits" field.
func HitsGTE(v int64) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldGTE(FieldHits, v))
}

// HitsLT applies the LT predicate on the "hits" field.
func HitsLT(v int64) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldLT(FieldHits, v))
}

// HitsLTE applies the LTE predicate on the "hits" field.
func HitsLTE(v int64) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldLTE(FieldHits, v))
}

// ValidatedEQ applies the EQ predicate on the "validated" field.
func ValidatedEQ(v bool) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEQ(FieldValidated, v))
}

// ValidatedNEQ applies the NEQ predicate on the "validated" field.
func ValidatedNEQ(v bool) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldNEQ(FieldValidated, v))
}

// DisabledEQ applies the EQ predicate on the "disabled" field.
func DisabledEQ(v bool) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEQ(FieldDisabled, v))
}

// DisabledNEQ applies the NEQ predicate on the "disabled" field.
func DisabledNEQ(v bool) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldNEQ(FieldDisabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldLTE(FieldUpdatedAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.Shortlink {
	return predicate.Shortlink(sql.FieldLTE(FieldExpiresAt, v))
}

// ExpiresAtIsNil applies the IsNil predicate on the "expires_at" field.
func ExpiresAtIsNil() predicate.Shortlink {
	return predicate.Shortlink(sql.FieldIsNull(FieldExpiresAt))
}

// ExpiresAtNotNil applies the NotNil predicate on the "expires_at" field.
func ExpiresAtNotNil() predicate.Shortlink {
	return predicate.Shortlink(sql.FieldNotNull(FieldExpiresAt))
}

// HasCreator applies the HasEdge predicate on the "creator" edge.
func HasCreator() predicate.Shortlink {
	return predicate.Shortlink(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CreatorTable, CreatorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCreatorWith applies the HasEdge predicate on the "creator" edge with a given conditions (other predicates).
func HasCreatorWith(preds ...predicate.User) predicate.Shortlink {
	return predicate.Shortlink(func(s *sql.Selector) {
		step := newCreatorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Shortlink) predicate.Shortlink {
	return predicate.Shortlink(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Shortlink) predicate.Shortlink {
	return predicate.Shortlink(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Shortlink) predicate.Shortlink {
	return predicate.Shortlink(sql.NotPredicates(p))
}
