// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ShortlinksColumns holds the columns for the "shortlinks" table.
	ShortlinksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "creator_ip", Type: field.TypeString},
		{Name: "shortcode", Type: field.TypeString, Unique: true},
		{Name: "shortlink", Type: field.TypeString, Unique: true},
		{Name: "destination", Type: field.TypeString},
		{Name: "secret_key", Type: field.TypeString, Unique: true},
		{Name: "hits", Type: field.TypeInt64, Default: 0},
		{Name: "validated", Type: field.TypeBool, Default: false},
		{Name: "disabled", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_shortlinks", Type: field.TypeUUID, Nullable: true},
	}
	// ShortlinksTable holds the schema information for the "shortlinks" table.
	ShortlinksTable = &schema.Table{
		Name:       "shortlinks",
		Columns:    ShortlinksColumns,
		PrimaryKey: []*schema.Column{ShortlinksColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "shortlinks_users_shortlinks",
				Columns:    []*schema.Column{ShortlinksColumns[12]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "shortlink_expires_at",
				Unique:  false,
				Columns: []*schema.Column{ShortlinksColumns[11]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "username", Type: field.TypeString},
		{Name: "sub", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "api_key", Type: field.TypeUUID, Unique: true},
		{Name: "admin", Type: field.TypeBool, Default: false},
		{Name: "reset_api_key_at", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ShortlinksTable,
		UsersTable,
	}
)

func init() {
	ShortlinksTable.ForeignKeys[0].RefTable = UsersTable
}
