// Code generated by ent, DO NOT EDIT.

package ent

import (
	"go-tetra/ent/schema"
	"go-tetra/ent/shortlink"
	"go-tetra/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	shortlinkFields := schema.Shortlink{}.Fields()
	_ = shortlinkFields
	// shortlinkDescCreatorIP is the schema descriptor for creator_ip field.
	shortlinkDescCreatorIP := shortlinkFields[1].Descriptor()
	// shortlink.CreatorIPValidator is a validator for the "creator_ip" field. It is called by the builders before save.
	shortlink.CreatorIPValidator = shortlinkDescCreatorIP.Validators[0].(func(string) error)
	// shortlinkDescShortcode is the schema descriptor for shortcode field.
	shortlinkDescShortcode := shortlinkFields[2].Descriptor()
	// shortlink.ShortcodeValidator is a validator for the "shortcode" field. It is called by the builders before save.
	shortlink.ShortcodeValidator = shortlinkDescShortcode.Validators[0].(func(string) error)
	// shortlinkDescShortlink is the schema descriptor for shortlink field.
	shortlinkDescShortlink := shortlinkFields[3].Descriptor()
	// shortlink.ShortlinkValidator is a validator for the "shortlink" field. It is called by the builders before save.
	shortlink.ShortlinkValidator = shortlinkDescShortlink.Validators[0].(func(string) error)
	// shortlinkDescDestination is the schema descriptor for destination field.
	shortlinkDescDestination := shortlinkFields[4].Descriptor()
	// shortlink.DestinationValidator is a validator for the "destination" field. It is called by the builders before save.
	shortlink.DestinationValidator = shortlinkDescDestination.Validators[0].(func(string) error)
	// shortlinkDescSecretKey is the schema descriptor for secret_key field.
	shortlinkDescSecretKey := shortlinkFields[5].Descriptor()
	// shortlink.SecretKeyValidator is a validator for the "secret_key" field. It is called by the builders before save.
	shortlink.SecretKeyValidator = shortlinkDescSecretKey.Validators[0].(func(string) error)
	// shortlinkDescHits is the schema descriptor for hits field.
	shortlinkDescHits := shortlinkFields[6].Descriptor()
	// shortlink.DefaultHits holds the default value on creation for the hits field.
	shortlink.DefaultHits = shortlinkDescHits.Default.(int64)
	// shortlinkDescValidated is the schema descriptor for validated field.
	shortlinkDescValidated := shortlinkFields[7].Descriptor()
	// shortlink.DefaultValidated holds the default value on creation for the validated field.
	shortlink.DefaultValidated = shortlinkDescValidated.Default.(bool)
	// shortlinkDescDisabled is the schema descriptor for disabled field.
	shortlinkDescDisabled := shortlinkFields[8].Descriptor()
	// shortlink.DefaultDisabled holds the default value on creation for the disabled field.
	shortlink.DefaultDisabled = shortlinkDescDisabled.Default.(bool)
	// shortlinkDescCreatedAt is the schema descriptor for created_at field.
	shortlinkDescCreatedAt := shortlinkFields[9].Descriptor()
	// shortlink.DefaultCreatedAt holds the default value on creation for the created_at field.
	shortlink.DefaultCreatedAt = shortlinkDescCreatedAt.Default.(func() time.Time)
	// shortlinkDescUpdatedAt is the schema descriptor for updated_at field.
	shortlinkDescUpdatedAt := shortlinkFields[10].Descriptor()
	// shortlink.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	shortlink.DefaultUpdatedAt = shortlinkDescUpdatedAt.Default.(func() time.Time)
	// shortlink.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	shortlink.UpdateDefaultUpdatedAt = shortlinkDescUpdatedAt.UpdateDefault.(func() time.Time)
	// shortlinkDescID is the schema descriptor for id field.
	shortlinkDescID := shortlinkFields[0].Descriptor()
	// shortlink.DefaultID holds the default value on creation for the id field.
	shortlink.DefaultID = shortlinkDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[1].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescSub is the schema descriptor for sub field.
	userDescSub := userFields[2].Descriptor()
	// user.SubValidator is a validator for the "sub" field. It is called by the builders before save.
	user.SubValidator = userDescSub.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[3].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescAPIKey is the schema descriptor for api_key field.
	userDescAPIKey := userFields[4].Descriptor()
	// user.DefaultAPIKey holds the default value on creation for the api_key field.
	user.DefaultAPIKey = userDescAPIKey.Default.(func() uuid.UUID)
	// userDescAdmin is the schema descriptor for admin field.
	userDescAdmin := userFields[5].Descriptor()
	// user.DefaultAdmin holds the default value on creation for the admin field.
	user.DefaultAdmin = userDescAdmin.Default.(bool)
	// userDescResetAPIKeyAt is the schema descriptor for reset_api_key_at field.
	userDescResetAPIKeyAt := userFields[6].Descriptor()
	// user.DefaultResetAPIKeyAt holds the default value on creation for the reset_api_key_at field.
	user.DefaultResetAPIKeyAt = userDescResetAPIKeyAt.Default.(func() time.Time)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[7].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[8].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
