// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-tetra/ent/shortlink"
	"go-tetra/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// Shortlink is the model entity for the Shortlink schema.
type Shortlink struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatorIP holds the value of the "creator_ip" field.
	CreatorIP string `json:"creator_ip,omitempty"`
	// Shortcode holds the value of the "shortcode" field.
	Shortcode string `json:"shortcode,omitempty"`
	// Shortlink holds the value of the "shortlink" field.
	Shortlink string `json:"shortlink,omitempty"`
	// Destination holds the value of the "destination" field.
	Destination string `json:"destination,omitempty"`
	// SecretKey holds the value of the "secret_key" field.
	SecretKey string `json:"secret_key,omitempty"`
	// Hits holds the value of the "hits" field.
	Hits int64 `json:"hits,omitempty"`
	// Validated holds the value of the "validated" field.
	Validated bool `json:"validated,omitempty"`
	// Disabled holds the value of the "disabled" field.
	Disabled bool `json:"disabled,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ShortlinkQuery when eager-loading is set.
	Edges           ShortlinkEdges `json:"edges"`
	user_shortlinks *uuid.UUID
	selectValues    sql.SelectValues
}

// ShortlinkEdges holds the relations/edges for other nodes in the graph.
type ShortlinkEdges struct {
	// Creator holds the value of the creator edge.
	Creator *User `json:"creator,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CreatorOrErr returns the Creator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ShortlinkEdges) CreatorOrErr() (*User, error) {
	if e.Creator != nil {
		return e.Creator, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "creator"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Shortlink) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case shortlink.FieldValidated, shortlink.FieldDisabled:
			values[i] = new(sql.NullBool)
		case shortlink.FieldHits:
			values[i] = new(sql.NullInt64)
		case shortlink.FieldCreatorIP, shortlink.FieldShortcode, shortlink.FieldShortlink, shortlink.FieldDestination, shortlink.FieldSecretKey:
			values[i] = new(sql.NullString)
		case shortlink.FieldCreatedAt, shortlink.FieldUpdatedAt, shortlink.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		case shortlink.FieldID:
			values[i] = new(uuid.UUID)
		case shortlink.ForeignKeys[0]: // user_shortlinks
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Shortlink fields.
func (_m *Shortlink) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case shortlink.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case shortlink.FieldCreatorIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field creator_ip", values[i])
			} else if value.Valid {
				_m.CreatorIP = value.String
			}
		case shortlink.FieldShortcode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field shortcode", values[i])
			} else if value.Valid {
				_m.Shortcode = value.String
			}
		case shortlink.FieldShortlink:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field shortlink", values[i])
			} else if value.Valid {
				_m.Shortlink = value.String
			}
		case shortlink.FieldDestination:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field destination", values[i])
			} else if value.Valid {
				_m.Destination = value.String
			}
		case shortlink.FieldSecretKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field secret_key", values[i])
			} else if value.Valid {
				_m.SecretKey = value.String
			}
		case shortlink.FieldHits:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field hits", values[i])
			} else if value.Valid {
				_m.Hits = value.Int64
			}
		case shortlink.FieldValidated:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field validated", values[i])
			} else if value.Valid {
				_m.Validated = value.Bool
			}
		case shortlink.FieldDisabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field disabled", values[i])
			} else if value.Valid {
				_m.Disabled = value.Bool
			}
		case shortlink.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case shortlink.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case shortlink.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case shortlink.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_shortlinks", values[i])
			} else if value.Valid {
				_m.user_shortlinks = new(uuid.UUID)
				*_m.user_shortlinks = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Shortlink.
// This includes values selected through modifiers, order, etc.
func (_m *Shortlink) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryCreator queries the "creator" edge of the Shortlink entity.
func (_m *Shortlink) QueryCreator() *UserQuery {
	return NewShortlinkClient(_m.config).QueryCreator(_m)
}

// Update returns a builder for updating this Shortlink.
// Note that you need to call Shortlink.Unwrap() before calling this method if this Shortlink
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Shortlink) Update() *ShortlinkUpdateOne {
	return NewShortlinkClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Shortlink entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Shortlink) Unwrap() *Shortlink {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Shortlink is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Shortlink) String() string {
	var builder strings.Builder
	builder.WriteString("Shortlink(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("creator_ip=")
	builder.WriteString(_m.CreatorIP)
	builder.WriteString(", ")
	builder.WriteString("shortcode=")
	builder.WriteString(_m.Shortcode)
	builder.WriteString(", ")
	builder.WriteString("shortlink=")
	builder.WriteString(_m.Shortlink)
	builder.WriteString(", ")
	builder.WriteString("destination=")
	builder.WriteString(_m.Destination)
	builder.WriteString(", ")
	builder.WriteString("secret_key=")
	builder.WriteString(_m.SecretKey)
	builder.WriteString(", ")
	builder.WriteString("hits=")
	builder.WriteString(fmt.Sprintf("%v", _m.Hits))
	builder.WriteString(", ")
	builder.WriteString("validated=")
	builder.WriteString(fmt.Sprintf("%v", _m.Validated))
	builder.WriteString(", ")
	builder.WriteString("disabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Disabled))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Shortlinks is a parsable slice of Shortlink.
type Shortlinks []*Shortlink
