// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"go-tetra/ent/predicate"
	"go-tetra/ent/shortlink"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ShortlinkDelete is the builder for deleting a Shortlink entity.
type ShortlinkDelete struct {
	config
	hooks    []Hook
	mutation *ShortlinkMutation
}

// Where appends a list predicates to the ShortlinkDelete builder.
func (_d *ShortlinkDelete) Where(ps ...predicate.Shortlink) *ShortlinkDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ShortlinkDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ShortlinkDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ShortlinkDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(shortlink.Table, sqlgraph.NewFieldSpec(shortlink.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ShortlinkDeleteOne is the builder for deleting a single Shortlink entity.
type ShortlinkDeleteOne struct {
	_d *ShortlinkDelete
}

// Where appends a list predicates to the ShortlinkDelete builder.
func (_d *ShortlinkDeleteOne) Where(ps ...predicate.Shortlink) *ShortlinkDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ShortlinkDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{shortlink.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ShortlinkDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
