// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-tetra/ent/shortlink"
	"go-tetra/ent/user"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ShortlinkCreate is the builder for creating a Shortlink entity.
type ShortlinkCreate struct {
	config
	mutation *ShortlinkMutation
	hooks    []Hook
}

// SetCreatorIP sets the "creator_ip" field.
func (_c *ShortlinkCreate) SetCreatorIP(v string) *ShortlinkCreate {
	_c.mutation.SetCreatorIP(v)
	return _c
}

// SetShortcode sets the "shortcode" field.
func (_c *ShortlinkCreate) SetShortcode(v string) *ShortlinkCreate {
	_c.mutation.SetShortcode(v)
	return _c
}

// SetShortlink sets the "shortlink" field.
func (_c *ShortlinkCreate) SetShortlink(v string) *ShortlinkCreate {
	_c.mutation.SetShortlink(v)
	return _c
}

// SetDestination sets the "destination" field.
func (_c *ShortlinkCreate) SetDestination(v string) *ShortlinkCreate {
	_c.mutation.SetDestination(v)
	return _c
}

// SetSecretKey sets the "secret_key" field.
func (_c *ShortlinkCreate) SetSecretKey(v string) *ShortlinkCreate {
	_c.mutation.SetSecretKey(v)
	return _c
}

// SetHits sets the "hits" field.
func (_c *ShortlinkCreate) SetHits(v int64) *ShortlinkCreate {
	_c.mutation.SetHits(v)
	return _c
}

// SetNillableHits sets the "hits" field if the given value is not nil.
func (_c *ShortlinkCreate) SetNillableHits(v *int64) *ShortlinkCreate {
	if v != nil {
		_c.SetHits(*v)
	}
	return _c
}

// SetValidated sets the "validated" field.
func (_c *ShortlinkCreate) SetValidated(v bool) *ShortlinkCreate {
	_c.mutation.SetValidated(v)
	return _c
}

// SetNillableValidated sets the "validated" field if the given value is not nil.
func (_c *ShortlinkCreate) SetNillableValidated(v *bool) *ShortlinkCreate {
	if v != nil {
		_c.SetValidated(*v)
	}
	return _c
}

// SetDisabled sets the "disabled" field.
func (_c *ShortlinkCreate) SetDisabled(v bool) *ShortlinkCreate {
	_c.mutation.SetDisabled(v)
	return _c
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_c *ShortlinkCreate) SetNillableDisabled(v *bool) *ShortlinkCreate {
	if v != nil {
		_c.SetDisabled(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ShortlinkCreate) SetCreatedAt(v time.Time) *ShortlinkCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ShortlinkCreate) SetNillableCreatedAt(v *time.Time) *ShortlinkCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ShortlinkCreate) SetUpdatedAt(v time.Time) *ShortlinkCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ShortlinkCreate) SetNillableUpdatedAt(v *time.Time) *ShortlinkCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *ShortlinkCreate) SetExpiresAt(v time.Time) *ShortlinkCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_c *ShortlinkCreate) SetNillableExpiresAt(v *time.Time) *ShortlinkCreate {
	if v != nil {
		_c.SetExpiresAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ShortlinkCreate) SetID(v uuid.UUID) *ShortlinkCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ShortlinkCreate) SetNillableID(v *uuid.UUID) *ShortlinkCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_c *ShortlinkCreate) SetCreatorID(id uuid.UUID) *ShortlinkCreate {
	_c.mutation.SetCreatorID(id)
	return _c
}

// SetNillableCreatorID sets the "creator" edge to the User entity by ID if the given value is not nil.
func (_c *ShortlinkCreate) SetNillableCreatorID(id *uuid.UUID) *ShortlinkCreate {
	if id != nil {
		_c = _c.SetCreatorID(*id)
	}
	return _c
}

// SetCreator sets the "creator" edge to the User entity.
func (_c *ShortlinkCreate) SetCreator(v *User) *ShortlinkCreate {
	return _c.SetCreatorID(v.ID)
}

// Mutation returns the ShortlinkMutation object of the builder.
func (_c *ShortlinkCreate) Mutation() *ShortlinkMutation {
	return _c.mutation
}

// Save creates the Shortlink in the database.
func (_c *ShortlinkCreate) Save(ctx context.Context) (*Shortlink, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ShortlinkCreate) SaveX(ctx context.Context) *Shortlink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShortlinkCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShortlinkCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ShortlinkCreate) defaults() {
	if _, ok := _c.mutation.Hits(); !ok {
		v := shortlink.DefaultHits
		_c.mutation.SetHits(v)
	}
	if _, ok := _c.mutation.Validated(); !ok {
		v := shortlink.DefaultValidated
		_c.mutation.SetValidated(v)
	}
	if _, ok := _c.mutation.Disabled(); !ok {
		v := shortlink.DefaultDisabled
		_c.mutation.SetDisabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := shortlink.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := shortlink.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := shortlink.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ShortlinkCreate) check() error {
	if _, ok := _c.mutation.CreatorIP(); !ok {
		return &ValidationError{Name: "creator_ip", err: errors.New(`ent: missing required field "Shortlink.creator_ip"`)}
	}
	if v, ok := _c.mutation.CreatorIP(); ok {
		if err := shortlink.CreatorIPValidator(v); err != nil {
			return &ValidationError{Name: "creator_ip", err: fmt.Errorf(`ent: validator failed for field "Shortlink.creator_ip": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Shortcode(); !ok {
		return &ValidationError{Name: "shortcode", err: errors.New(`ent: missing required field "Shortlink.shortcode"`)}
	}
	if v, ok := _c.mutation.Shortcode(); ok {
		if err := shortlink.ShortcodeValidator(v); err != nil {
			return &ValidationError{Name: "shortcode", err: fmt.Errorf(`ent: validator failed for field "Shortlink.shortcode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Shortlink(); !ok {
		return &ValidationError{Name: "shortlink", err: errors.New(`ent: missing required field "Shortlink.shortlink"`)}
	}
	if v, ok := _c.mutation.Shortlink(); ok {
		if err := shortlink.ShortlinkValidator(v); err != nil {
			return &ValidationError{Name: "shortlink", err: fmt.Errorf(`ent: validator failed for field "Shortlink.shortlink": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Destination(); !ok {
		return &ValidationError{Name: "destination", err: errors.New(`ent: missing required field "Shortlink.destination"`)}
	}
	if v, ok := _c.mutation.Destination(); ok {
		if err := shortlink.DestinationValidator(v); err != nil {
			return &ValidationError{Name: "destination", err: fmt.Errorf(`ent: validator failed for field "Shortlink.destination": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SecretKey(); !ok {
		return &ValidationError{Name: "secret_key", err: errors.New(`ent: missing required field "Shortlink.secret_key"`)}
	}
	if v, ok := _c.mutation.SecretKey(); ok {
		if err := shortlink.SecretKeyValidator(v); err != nil {
			return &ValidationError{Name: "secret_key", err: fmt.Errorf(`ent: validator failed for field "Shortlink.secret_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Hits(); !ok {
		return &ValidationError{Name: "hits", err: errors.New(`ent: missing required field "Shortlink.hits"`)}
	}
	if _, ok := _c.mutation.Validated(); !ok {
		return &ValidationError{Name: "validated", err: errors.New(`ent: missing required field "Shortlink.validated"`)}
	}
	if _, ok := _c.mutation.Disabled(); !ok {
		return &ValidationError{Name: "disabled", err: errors.New(`ent: missing required field "Shortlink.disabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Shortlink.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Shortlink.updated_at"`)}
	}
	return nil
}

func (_c *ShortlinkCreate) sqlSave(ctx context.Context) (*Shortlink, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ShortlinkCreate) createSpec() (*Shortlink, *sqlgraph.CreateSpec) {
	var (
		_node = &Shortlink{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(shortlink.Table, sqlgraph.NewFieldSpec(shortlink.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatorIP(); ok {
		_spec.SetField(shortlink.FieldCreatorIP, field.TypeString, value)
		_node.CreatorIP = value
	}
	if value, ok := _c.mutation.Shortcode(); ok {
		_spec.SetField(shortlink.FieldShortcode, field.TypeString, value)
		_node.Shortcode = value
	}
	if value, ok := _c.mutation.Shortlink(); ok {
		_spec.SetField(shortlink.FieldShortlink, field.TypeString, value)
		_node.Shortlink = value
	}
	if value, ok := _c.mutation.Destination(); ok {
		_spec.SetField(shortlink.FieldDestination, field.TypeString, value)
		_node.Destination = value
	}
	if value, ok := _c.mutation.SecretKey(); ok {
		_spec.SetField(shortlink.FieldSecretKey, field.TypeString, value)
		_node.SecretKey = value
	}
	if value, ok := _c.mutation.Hits(); ok {
		_spec.SetField(shortlink.FieldHits, field.TypeInt64, value)
		_node.Hits = value
	}
	if value, ok := _c.mutation.Validated(); ok {
		_spec.SetField(shortlink.FieldValidated, field.TypeBool, value)
		_node.Validated = value
	}
	if value, ok := _c.mutation.Disabled(); ok {
		_spec.SetField(shortlink.FieldDisabled, field.TypeBool, value)
		_node.Disabled = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(shortlink.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(shortlink.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(shortlink.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = &value
	}
	if nodes := _c.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shortlink.CreatorTable,
			Columns: []string{shortlink.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_shortlinks = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ShortlinkCreateBulk is the builder for creating many Shortlink entities in bulk.
type ShortlinkCreateBulk struct {
	config
	err      error
	builders []*ShortlinkCreate
}

// Save creates the Shortlink entities in the database.
func (_c *ShortlinkCreateBulk) Save(ctx context.Context) ([]*Shortlink, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Shortlink, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ShortlinkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ShortlinkCreateBulk) SaveX(ctx context.Context) []*Shortlink {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ShortlinkCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ShortlinkCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
