// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-tetra/ent/predicate"
	"go-tetra/ent/shortlink"
	"go-tetra/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ShortlinkUpdate is the builder for updating Shortlink entities.
type ShortlinkUpdate struct {
	config
	hooks    []Hook
	mutation *ShortlinkMutation
}

// Where appends a list predicates to the ShortlinkUpdate builder.
func (_u *ShortlinkUpdate) Where(ps ...predicate.Shortlink) *ShortlinkUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreatorIP sets the "creator_ip" field.
func (_u *ShortlinkUpdate) SetCreatorIP(v string) *ShortlinkUpdate {
	_u.mutation.SetCreatorIP(v)
	return _u
}

// SetNillableCreatorIP sets the "creator_ip" field if the given value is not nil.
func (_u *ShortlinkUpdate) SetNillableCreatorIP(v *string) *ShortlinkUpdate {
	if v != nil {
		_u.SetCreatorIP(*v)
	}
	return _u
}

// SetShortcode sets the "shortcode" field.
func (_u *ShortlinkUpdate) SetShortcode(v string) *ShortlinkUpdate {
	_u.mutation.SetShortcode(v)
	return _u
}

// SetNillableShortcode sets the "shortcode" field if the given value is not nil.
func (_u *ShortlinkUpdate) SetNillableShortcode(v *string) *ShortlinkUpdate {
	if v != nil {
		_u.SetShortcode(*v)
	}
	return _u
}

// SetShortlink sets the "shortlink" field.
func (_u *ShortlinkUpdate) SetShortlink(v string) *ShortlinkUpdate {
	_u.mutation.SetShortlink(v)
	return _u
}

// SetNillableShortlink sets the "shortlink" field if the given value is not nil.
func (_u *ShortlinkUpdate) SetNillableShortlink(v *string) *ShortlinkUpdate {
	if v != nil {
		_u.SetShortlink(*v)
	}
	return _u
}

// SetDestination sets the "destination" field.
func (_u *ShortlinkUpdate) SetDestination(v string) *ShortlinkUpdate {
	_u.mutation.SetDestination(v)
	return _u
}

// SetNillableDestination sets the "destination" field if the given value is not nil.
func (_u *ShortlinkUpdate) SetNillableDestination(v *string) *ShortlinkUpdate {
	if v != nil {
		_u.SetDestination(*v)
	}
	return _u
}

// SetSecretKey sets the "secret_key" field.
func (_u *ShortlinkUpdate) SetSecretKey(v string) *ShortlinkUpdate {
	_u.mutation.SetSecretKey(v)
	return _u
}

// SetNillableSecretKey sets the "secret_key" field if the given value is not nil.
func (_u *ShortlinkUpdate) SetNillableSecretKey(v *string) *ShortlinkUpdate {
	if v != nil {
		_u.SetSecretKey(*v)
	}
	return _u
}

// SetHits sets the "hits" field.
func (_u *ShortlinkUpdate) SetHits(v int64) *ShortlinkUpdate {
	_u.mutation.ResetHits()
	_u.mutation.SetHits(v)
	return _u
}

// SetNillableHits sets the "hits" field if the given value is not nil.
func (_u *ShortlinkUpdate) SetNillableHits(v *int64) *ShortlinkUpdate {
	if v != nil {
		_u.SetHits(*v)
	}
	return _u
}

// AddHits adds value to the "hits" field.
func (_u *ShortlinkUpdate) AddHits(v int64) *ShortlinkUpdate {
	_u.mutation.AddHits(v)
	return _u
}

// SetValidated sets the "validated" field.
func (_u *ShortlinkUpdate) SetValidated(v bool) *ShortlinkUpdate {
	_u.mutation.SetValidated(v)
	return _u
}

// SetNillableValidated sets the "validated" field if the given value is not nil.
func (_u *ShortlinkUpdate) SetNillableValidated(v *bool) *ShortlinkUpdate {
	if v != nil {
		_u.SetValidated(*v)
	}
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *ShortlinkUpdate) SetDisabled(v bool) *ShortlinkUpdate {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *ShortlinkUpdate) SetNillableDisabled(v *bool) *ShortlinkUpdate {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ShortlinkUpdate) SetUpdatedAt(v time.Time) *ShortlinkUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ShortlinkUpdate) SetExpiresAt(v time.Time) *ShortlinkUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ShortlinkUpdate) SetNillableExpiresAt(v *time.Time) *ShortlinkUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ShortlinkUpdate) ClearExpiresAt() *ShortlinkUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *ShortlinkUpdate) SetCreatorID(id uuid.UUID) *ShortlinkUpdate {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetNillableCreatorID sets the "creator" edge to the User entity by ID if the given value is not nil.
func (_u *ShortlinkUpdate) SetNillableCreatorID(id *uuid.UUID) *ShortlinkUpdate {
	if id != nil {
		_u = _u.SetCreatorID(*id)
	}
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *ShortlinkUpdate) SetCreator(v *User) *ShortlinkUpdate {
	return _u.SetCreatorID(v.ID)
}

// Mutation returns the ShortlinkMutation object of the builder.
func (_u *ShortlinkUpdate) Mutation() *ShortlinkMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *ShortlinkUpdate) ClearCreator() *ShortlinkUpdate {
	_u.mutation.ClearCreator()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ShortlinkUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ShortlinkUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ShortlinkUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ShortlinkUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ShortlinkUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := shortlink.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ShortlinkUpdate) check() error {
	if v, ok := _u.mutation.CreatorIP(); ok {
		if err := shortlink.CreatorIPValidator(v); err != nil {
			return &ValidationError{Name: "creator_ip", err: fmt.Errorf(`ent: validator failed for field "Shortlink.creator_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Shortcode(); ok {
		if err := shortlink.ShortcodeValidator(v); err != nil {
			return &ValidationError{Name: "shortcode", err: fmt.Errorf(`ent: validator failed for field "Shortlink.shortcode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Shortlink(); ok {
		if err := shortlink.ShortlinkValidator(v); err != nil {
			return &ValidationError{Name: "shortlink", err: fmt.Errorf(`ent: validator failed for field "Shortlink.shortlink": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Destination(); ok {
		if err := shortlink.DestinationValidator(v); err != nil {
			return &ValidationError{Name: "destination", err: fmt.Errorf(`ent: validator failed for field "Shortlink.destination": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SecretKey(); ok {
		if err := shortlink.SecretKeyValidator(v); err != nil {
			return &ValidationError{Name: "secret_key", err: fmt.Errorf(`ent: validator failed for field "Shortlink.secret_key": %w`, err)}
		}
	}
	return nil
}

func (_u *ShortlinkUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(shortlink.Table, shortlink.Columns, sqlgraph.NewFieldSpec(shortlink.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatorIP(); ok {
		_spec.SetField(shortlink.FieldCreatorIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.Shortcode(); ok {
		_spec.SetField(shortlink.FieldShortcode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Shortlink(); ok {
		_spec.SetField(shortlink.FieldShortlink, field.TypeString, value)
	}
	if value, ok := _u.mutation.Destination(); ok {
		_spec.SetField(shortlink.FieldDestination, field.TypeString, value)
	}
	if value, ok := _u.mutation.SecretKey(); ok {
		_spec.SetField(shortlink.FieldSecretKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Hits(); ok {
		_spec.SetField(shortlink.FieldHits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedHits(); ok {
		_spec.AddField(shortlink.FieldHits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Validated(); ok {
		_spec.SetField(shortlink.FieldValidated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(shortlink.FieldDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(shortlink.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(shortlink.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(shortlink.FieldExpiresAt, field.TypeTime)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shortlink.CreatorTable,
			Columns: []string{shortlink.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shortlink.CreatorTable,
			Columns: []string{shortlink.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{shortlink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ShortlinkUpdateOne is the builder for updating a single Shortlink entity.
type ShortlinkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ShortlinkMutation
}

// SetCreatorIP sets the "creator_ip" field.
func (_u *ShortlinkUpdateOne) SetCreatorIP(v string) *ShortlinkUpdateOne {
	_u.mutation.SetCreatorIP(v)
	return _u
}

// SetNillableCreatorIP sets the "creator_ip" field if the given value is not nil.
func (_u *ShortlinkUpdateOne) SetNillableCreatorIP(v *string) *ShortlinkUpdateOne {
	if v != nil {
		_u.SetCreatorIP(*v)
	}
	return _u
}

// SetShortcode sets the "shortcode" field.
func (_u *ShortlinkUpdateOne) SetShortcode(v string) *ShortlinkUpdateOne {
	_u.mutation.SetShortcode(v)
	return _u
}

// SetNillableShortcode sets the "shortcode" field if the given value is not nil.
func (_u *ShortlinkUpdateOne) SetNillableShortcode(v *string) *ShortlinkUpdateOne {
	if v != nil {
		_u.SetShortcode(*v)
	}
	return _u
}

// SetShortlink sets the "shortlink" field.
func (_u *ShortlinkUpdateOne) SetShortlink(v string) *ShortlinkUpdateOne {
	_u.mutation.SetShortlink(v)
	return _u
}

// SetNillableShortlink sets the "shortlink" field if the given value is not nil.
func (_u *ShortlinkUpdateOne) SetNillableShortlink(v *string) *ShortlinkUpdateOne {
	if v != nil {
		_u.SetShortlink(*v)
	}
	return _u
}

// SetDestination sets the "destination" field.
func (_u *ShortlinkUpdateOne) SetDestination(v string) *ShortlinkUpdateOne {
	_u.mutation.SetDestination(v)
	return _u
}

// SetNillableDestination sets the "destination" field if the given value is not nil.
func (_u *ShortlinkUpdateOne) SetNillableDestination(v *string) *ShortlinkUpdateOne {
	if v != nil {
		_u.SetDestination(*v)
	}
	return _u
}

// SetSecretKey sets the "secret_key" field.
func (_u *ShortlinkUpdateOne) SetSecretKey(v string) *ShortlinkUpdateOne {
	_u.mutation.SetSecretKey(v)
	return _u
}

// SetNillableSecretKey sets the "secret_key" field if the given value is not nil.
func (_u *ShortlinkUpdateOne) SetNillableSecretKey(v *string) *ShortlinkUpdateOne {
	if v != nil {
		_u.SetSecretKey(*v)
	}
	return _u
}

// SetHits sets the "hits" field.
func (_u *ShortlinkUpdateOne) SetHits(v int64) *ShortlinkUpdateOne {
	_u.mutation.ResetHits()
	_u.mutation.SetHits(v)
	return _u
}

// SetNillableHits sets the "hits" field if the given value is not nil.
func (_u *ShortlinkUpdateOne) SetNillableHits(v *int64) *ShortlinkUpdateOne {
	if v != nil {
		_u.SetHits(*v)
	}
	return _u
}

// AddHits adds value to the "hits" field.
func (_u *ShortlinkUpdateOne) AddHits(v int64) *ShortlinkUpdateOne {
	_u.mutation.AddHits(v)
	return _u
}

// SetValidated sets the "validated" field.
func (_u *ShortlinkUpdateOne) SetValidated(v bool) *ShortlinkUpdateOne {
	_u.mutation.SetValidated(v)
	return _u
}

// SetNillableValidated sets the "validated" field if the given value is not nil.
func (_u *ShortlinkUpdateOne) SetNillableValidated(v *bool) *ShortlinkUpdateOne {
	if v != nil {
		_u.SetValidated(*v)
	}
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *ShortlinkUpdateOne) SetDisabled(v bool) *ShortlinkUpdateOne {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *ShortlinkUpdateOne) SetNillableDisabled(v *bool) *ShortlinkUpdateOne {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ShortlinkUpdateOne) SetUpdatedAt(v time.Time) *ShortlinkUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *ShortlinkUpdateOne) SetExpiresAt(v time.Time) *ShortlinkUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ShortlinkUpdateOne) SetNillableExpiresAt(v *time.Time) *ShortlinkUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ShortlinkUpdateOne) ClearExpiresAt() *ShortlinkUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
}

// SetCreatorID sets the "creator" edge to the User entity by ID.
func (_u *ShortlinkUpdateOne) SetCreatorID(id uuid.UUID) *ShortlinkUpdateOne {
	_u.mutation.SetCreatorID(id)
	return _u
}

// SetNillableCreatorID sets the "creator" edge to the User entity by ID if the given value is not nil.
func (_u *ShortlinkUpdateOne) SetNillableCreatorID(id *uuid.UUID) *ShortlinkUpdateOne {
	if id != nil {
		_u = _u.SetCreatorID(*id)
	}
	return _u
}

// SetCreator sets the "creator" edge to the User entity.
func (_u *ShortlinkUpdateOne) SetCreator(v *User) *ShortlinkUpdateOne {
	return _u.SetCreatorID(v.ID)
}

// Mutation returns the ShortlinkMutation object of the builder.
func (_u *ShortlinkUpdateOne) Mutation() *ShortlinkMutation {
	return _u.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (_u *ShortlinkUpdateOne) ClearCreator() *ShortlinkUpdateOne {
	_u.mutation.ClearCreator()
	return _u
}

// Where appends a list predicates to the ShortlinkUpdate builder.
func (_u *ShortlinkUpdateOne) Where(ps ...predicate.Shortlink) *ShortlinkUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ShortlinkUpdateOne) Select(field string, fields ...string) *ShortlinkUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Shortlink entity.
func (_u *ShortlinkUpdateOne) Save(ctx context.Context) (*Shortlink, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ShortlinkUpdateOne) SaveX(ctx context.Context) *Shortlink {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ShortlinkUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ShortlinkUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ShortlinkUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := shortlink.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ShortlinkUpdateOne) check() error {
	if v, ok := _u.mutation.CreatorIP(); ok {
		if err := shortlink.CreatorIPValidator(v); err != nil {
			return &ValidationError{Name: "creator_ip", err: fmt.Errorf(`ent: validator failed for field "Shortlink.creator_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Shortcode(); ok {
		if err := shortlink.ShortcodeValidator(v); err != nil {
			return &ValidationError{Name: "shortcode", err: fmt.Errorf(`ent: validator failed for field "Shortlink.shortcode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Shortlink(); ok {
		if err := shortlink.ShortlinkValidator(v); err != nil {
			return &ValidationError{Name: "shortlink", err: fmt.Errorf(`ent: validator failed for field "Shortlink.shortlink": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Destination(); ok {
		if err := shortlink.DestinationValidator(v); err != nil {
			return &ValidationError{Name: "destination", err: fmt.Errorf(`ent: validator failed for field "Shortlink.destination": %w`, err)}
		}
	}
	if v, ok := _u.mutation.SecretKey(); ok {
		if err := shortlink.SecretKeyValidator(v); err != nil {
			return &ValidationError{Name: "secret_key", err: fmt.Errorf(`ent: validator failed for field "Shortlink.secret_key": %w`, err)}
		}
	}
	return nil
}

func (_u *ShortlinkUpdateOne) sqlSave(ctx context.Context) (_node *Shortlink, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(shortlink.Table, shortlink.Columns, sqlgraph.NewFieldSpec(shortlink.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Shortlink.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, shortlink.FieldID)
		for _, f := range fields {
			if !shortlink.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != shortlink.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreatorIP(); ok {
		_spec.SetField(shortlink.FieldCreatorIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.Shortcode(); ok {
		_spec.SetField(shortlink.FieldShortcode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Shortlink(); ok {
		_spec.SetField(shortlink.FieldShortlink, field.TypeString, value)
	}
	if value, ok := _u.mutation.Destination(); ok {
		_spec.SetField(shortlink.FieldDestination, field.TypeString, value)
	}
	if value, ok := _u.mutation.SecretKey(); ok {
		_spec.SetField(shortlink.FieldSecretKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Hits(); ok {
		_spec.SetField(shortlink.FieldHits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedHits(); ok {
		_spec.AddField(shortlink.FieldHits, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Validated(); ok {
		_spec.SetField(shortlink.FieldValidated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(shortlink.FieldDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(shortlink.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(shortlink.FieldExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(shortlink.FieldExpiresAt, field.TypeTime)
	}
	if _u.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shortlink.CreatorTable,
			Columns: []string{shortlink.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   shortlink.CreatorTable,
			Columns: []string{shortlink.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Shortlink{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{shortlink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
