name: Deploy
on:
  push:
    branches:
      - master
permissions:
  contents: read
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.super.fish
          username: robot$tetra+ci
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            docker.super.fish/tetra/tetra:latest
            docker.super.fish/tetra/tetra:${{ github.sha }}
