// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Shortlink is the predicate function for shortlink builders.
type Shortlink func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
